bgp_asn: 65000
router_id: "3.3.3.3"
bgp_neighbors:
  - ip: 192.168.62.2
    remote_as: 65000
    desc: "TO-ROUTER1"
  - ip: 192.168.62.3
    remote_as: 65000
    desc: "TO-ROUTER2"
bgp_networks:
  - network: 192.168.62.0
    mask: 255.255.255.0
